language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexacid88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexacid88/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-767507783469"
  bucket_path: "docker-react"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
