language: node_js
node_js:
- '12'
env:
- TRAVIS_NODE_VERSION="12.16"
sudo: required
services:
  - docker

before_install:
  - docker build -t alexacid88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexacid88/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "react"
  env: "develop"
  bucket_name: "elasticbeanstalk-us-east-1-767507783469"
  bucket_path: "react"
  on:
    branch: develop
  skip_cleanup: true
