language: node_js
node_js:
- '12'
env:
- TRAVIS_NODE_VERSION="12.16"
sudo: required
services:
  - docker

before_install:
  - docker build -t alexacid88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexacid88/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-west-2
  app: docker
  env: docker-dev
  bucket_name: elasticbeanstalk-us-west-2-767507783469
  bucket_path: docker
  on:
    branch: develop
  skip_cleanup: true
